# Grab the Alpine Linux image
FROM node:18-alpine3.16

# Set Env Vars
ENV DB_HOST=mysql
ENV DB_USER=root
ENV DB_PASSWORD=1234
ENV DB_NAME=budgetapp
ENV DB_PORT=3306

# Install npm and nodemon
RUN npm install -g npm
RUN npm install -g nodemon

# Install packages with npm
WORKDIR /app
COPY package*.json .
RUN npm install

# Copy source code to container
COPY . .

# Expose port 3000
EXPOSE 3000

# Run the image as a non-root user
RUN adduser -D myuser
USER myuser

# Run development script
CMD ["npm", "run", "dev"]
